<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto

namespace Gopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gopay.RefundRequest</code>
 */
class RefundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *1.0
     *
     * Generated from protobuf field <code>string version = 1;</code>
     */
    private $version = '';
    /**
     * Generated from protobuf field <code>string appId = 2;</code>
     */
    private $appId = '';
    /**
     * Generated from protobuf field <code>string appSecret = 3;</code>
     */
    private $appSecret = '';
    /**
     * Generated from protobuf field <code>string sn = 4;</code>
     */
    private $sn = '';
    /**
     * Generated from protobuf field <code>string tradeNo = 5;</code>
     */
    private $tradeNo = '';
    /**
     *退款总金额
     *
     * Generated from protobuf field <code>float totalAmount = 6;</code>
     */
    private $totalAmount = 0.0;
    /**
     *退款金额
     *
     * Generated from protobuf field <code>float amount = 7;</code>
     */
    private $amount = 0.0;
    /**
     *退款原因
     *
     * Generated from protobuf field <code>string remark = 8;</code>
     */
    private $remark = '';
    /**
     *1-微信 2-支付宝
     *
     * Generated from protobuf field <code>int32 refundType = 9;</code>
     */
    private $refundType = 0;
    /**
     * 1-app 2-小程序 3-公众号 4-pc
     *
     * Generated from protobuf field <code>int32 platform = 10;</code>
     */
    private $platform = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *          1.0
     *     @type string $appId
     *     @type string $appSecret
     *     @type string $sn
     *     @type string $tradeNo
     *     @type float $totalAmount
     *          退款总金额
     *     @type float $amount
     *          退款金额
     *     @type string $remark
     *          退款原因
     *     @type int $refundType
     *          1-微信 2-支付宝
     *     @type int $platform
     *           1-app 2-小程序 3-公众号 4-pc
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pay::initOnce();
        parent::__construct($data);
    }

    /**
     *1.0
     *
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *1.0
     *
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appId = 2;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * Generated from protobuf field <code>string appId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appSecret = 3;</code>
     * @return string
     */
    public function getAppSecret()
    {
        return $this->appSecret;
    }

    /**
     * Generated from protobuf field <code>string appSecret = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAppSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->appSecret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sn = 4;</code>
     * @return string
     */
    public function getSn()
    {
        return $this->sn;
    }

    /**
     * Generated from protobuf field <code>string sn = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSn($var)
    {
        GPBUtil::checkString($var, True);
        $this->sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tradeNo = 5;</code>
     * @return string
     */
    public function getTradeNo()
    {
        return $this->tradeNo;
    }

    /**
     * Generated from protobuf field <code>string tradeNo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tradeNo = $var;

        return $this;
    }

    /**
     *退款总金额
     *
     * Generated from protobuf field <code>float totalAmount = 6;</code>
     * @return float
     */
    public function getTotalAmount()
    {
        return $this->totalAmount;
    }

    /**
     *退款总金额
     *
     * Generated from protobuf field <code>float totalAmount = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalAmount($var)
    {
        GPBUtil::checkFloat($var);
        $this->totalAmount = $var;

        return $this;
    }

    /**
     *退款金额
     *
     * Generated from protobuf field <code>float amount = 7;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *退款金额
     *
     * Generated from protobuf field <code>float amount = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkFloat($var);
        $this->amount = $var;

        return $this;
    }

    /**
     *退款原因
     *
     * Generated from protobuf field <code>string remark = 8;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     *退款原因
     *
     * Generated from protobuf field <code>string remark = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->remark = $var;

        return $this;
    }

    /**
     *1-微信 2-支付宝
     *
     * Generated from protobuf field <code>int32 refundType = 9;</code>
     * @return int
     */
    public function getRefundType()
    {
        return $this->refundType;
    }

    /**
     *1-微信 2-支付宝
     *
     * Generated from protobuf field <code>int32 refundType = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setRefundType($var)
    {
        GPBUtil::checkInt32($var);
        $this->refundType = $var;

        return $this;
    }

    /**
     * 1-app 2-小程序 3-公众号 4-pc
     *
     * Generated from protobuf field <code>int32 platform = 10;</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * 1-app 2-小程序 3-公众号 4-pc
     *
     * Generated from protobuf field <code>int32 platform = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkInt32($var);
        $this->platform = $var;

        return $this;
    }

}

